### PR TITLE
[TESTS] allow all tests to run with all provider implementations

### PR DESCRIPTION
**Pull request by aricart**
[CHANGE] moved/renamed the providers

[FIX] tests now use a suite, which is set up for all providers; this allows all tests to be run with all provider implementations with minimal work

### CODE REVIEW

**Comment by aricart** [comment]
@ripienaar would like to borrow the contexts from the nats connection for the setup. some of the API will have to change to make it more granular

**Comment by ripienaar** [comment]
easy to use nats contexts.  `natscontext.Connect("CONTEXT_NAME", nats.MaxReconnects(-1), etc)` if CONTEXT_NAME is empty it uses the selected one.  If you wanted to support full paths to contexts do `natscontext.NewFromFile(fileName, opts...)`

**Comment by aricart** [comment]
@ripienaar I think this does what you want, also simplifies because there's a way to create by providing a connection directly

**Comment by ripienaar** [comment]
Cool yeah for CLI we'd probably just pass in the connection cos it already handles all the setup stuff itself

**Pull request merged**
