### PR TITLE
Allow user permission limits to be set as a struct

### PR DESCRIPTION
**Pull request by ripienaar**

### CODE REVIEW

**Review by aricart — APPROVED** [review]
I wanted to telegraph the jwt library, perhaps there's a way of having some local struct that turns into the JWT... but for now I think this is OK

**Comment by ripienaar** [comment]
Yeah agree, I considered not adding these to the interface and just cast to the type or other interface in the CLI - as in the normally done thing? I am ok with that if we dont want to fully bless this sort of thing - but all the Setters with error handling is super grim for something like that CLI

**Comment by ripienaar** [comment]
```
cli/auth_account_command.go | 53 +++++++++++++----------------------------------------
 cli/auth_user_command.go    | 46 ++++++++++------------------------------------
 2 files changed, 23 insertions(+), 76 deletions(-)
```

using these :)

**Comment by aricart** [comment]
Effectively, what you are looking for is ignoring all the error checking that happens and only do it on the set right?

**Comment by ripienaar** [comment]
Yes, I dont need to error check every set, one set error checking the whole set is enough - essentially its a single transaction all or nothing, so one error check.

**Comment by aricart** [comment]
Could it be as simple simple as a struct that is almost the same as the limits, with only a couple of functions to do things like `SetUnlimited()`

**Comment by aricart** [comment]
The only issue I see is that some of the names on the interface are more indicative - MaxConsumers instead of Consumers, but perhaps that is just a nit, and doesn't matter.

**Comment by ripienaar** [comment]
Maybe? would need to see how that looks - trying to keep duplication to a minimum from the jwt lib though

**Comment by aricart** [comment]
The other choice is to copy the struct from JWT, but not have the dep from the package exposed to the user code.

**Comment by ripienaar** [comment]
This also allows the lib to support esoteric things, remember we dont neccesarily want to surface every single tiny feature of the jwt libs in here, its what we think people will want to do often and its a bit oppinionated.

By taking the jwt struct we allow people to achieve weird thigns - maybe a bad thing?

**Comment by aricart** [comment]
the exposing simply means that we are bound to it - IMHO, the implementation in the future just stores a JSON that can be converted to a JWT.

**Comment by ripienaar** [comment]
I do want to add JSONMarshall() and JSONUnmarshall()

**Pull request merged**
